### PR TITLE
Fix capitalization 'GIt' to 'Git' in course description

### PR DESCRIPTION
**Pull request by kmolo**
...and since already editing also changed 'Github' to 'GitHub'

### CODE REVIEW

**Comment by kmolo** [comment]
Showing up as uncorrectable on events.openhatch.org, so had to fix via GitHub repo.  I hope this repo shaunagm/bridge_troll is the one (or connected to the one) connected to the live events.openhatch.org website.  Or is there another repo (instead of this one) that I should be interacting with?

**Comment by shaunagm** [comment]
It is the correct repo, but I need to manually push to Heroku.  Will try to get to that today.

**Comment by kmolo** [comment]
Will be curious to see if push to Heroku changes existing events, or only those created in the future.

**Comment by kmolo** [comment]
Push does not change existing events.  Even switched from 'OSCTCfull' to 'OSCTCsprint', saved; then re-edited & saved again as 'OSCTCfull' -- still old capitalization styles.  Hmmm, interesting...but will be fixed for future events.

**Pull request merged**
